import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Music, Star, Disc3, TrendingUp } from 'lucide-react';

export default function Home() {
  return (
    <div className="flex flex-col min-h-[calc(100vh-64px)] overflow-hidden relative">
      {/* Background Gradients */}
      <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-blue-900/30 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-purple-900/20 rounded-full blur-[120px] pointer-events-none" />

      <main className="flex-1 flex flex-col items-center justify-center p-8 text-center relative z-10 my-auto">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-zinc-900/50 border border-zinc-800 text-sm text-zinc-300 mb-8 backdrop-blur-sm">
          <Star className="w-4 h-4 text-yellow-500" />
          <span>The world's fastest-growing music community</span>
        </div>
        
        <h1 className="text-6xl md:text-8xl font-black mb-6 tracking-tight bg-gradient-to-br from-white via-zinc-200 to-zinc-500 bg-clip-text text-transparent max-w-4xl leading-tight pb-2">
          Discover, rate, and catalog your music.
        </h1>
        
        <p className="text-xl md:text-2xl text-zinc-400 max-w-2xl mb-10 leading-relaxed font-light">
          Audex is a vibrant community built for music nerds. Keep track of what you've heard, write reviews, and explore the top charts generated by millions of ratings.
        </p>
        
        <div className="flex flex-col sm:flex-row gap-4">
          <Link href="/charts">
            <Button size="lg" className="bg-white text-black hover:bg-zinc-200 text-lg rounded-full px-8 h-14 font-semibold shadow-[0_0_40px_rgba(255,255,255,0.2)] transition-all hover:scale-105">
              Explore Top Charts
            </Button>
          </Link>
          <Link href="/album/697194953">
            <Button size="lg" variant="outline" className="border-zinc-700 bg-zinc-900/50 backdrop-blur-md hover:bg-zinc-800 hover:text-white text-lg rounded-full px-8 h-14 font-semibold transition-all">
              View Example Album
            </Button>
          </Link>
        </div>

        {/* Feature grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-24 max-w-5xl w-full text-left">
          <div className="p-6 rounded-2xl bg-zinc-900/40 border border-zinc-800/50 backdrop-blur-sm">
            <Disc3 className="w-8 h-8 text-blue-400 mb-4" />
            <h3 className="text-xl font-bold text-white mb-2">Massive Database</h3>
            <p className="text-zinc-400">Search through millions of albums, EPs, and singles powered by our external API integration.</p>
          </div>
          <div className="p-6 rounded-2xl bg-zinc-900/40 border border-zinc-800/50 backdrop-blur-sm">
            <Star className="w-8 h-8 text-yellow-400 mb-4" />
            <h3 className="text-xl font-bold text-white mb-2">Detailed Ratings</h3>
            <p className="text-zinc-400">Rate your favorite albums on a 5-star scale (with half-stars) and write in-depth reviews.</p>
          </div>
          <div className="p-6 rounded-2xl bg-zinc-900/40 border border-zinc-800/50 backdrop-blur-sm">
            <TrendingUp className="w-8 h-8 text-green-400 mb-4" />
            <h3 className="text-xl font-bold text-white mb-2">Dynamic Charts</h3>
            <p className="text-zinc-400">Our charts are constantly updated based on aggregated community ratings and reviews.</p>
          </div>
        </div>
      </main>
    </div>
  );
}
